#!/system/bin/sh
## CronMod INT2EXT+ by croniccorey[at]xda-developers.com rewriten script
## All credits are belongs to croniccorey

bb=/system/xbin/busybox || /system/bin/busybox;
sdext=/sd-ext;
internal=`$bb mountpoint -n /data | awk '{print $1}'`;
extblock=/dev/block/mmcblk0p2;
log=/data/int2ext.log;
sdcache=/sys/devices/virtual/bdi/179\:0/read_ahead_kb;

logger() {
  if [ ! -e $log ]; then
    $bb touch $log;
    $bb chown root:root $log;
    $bb chmod 775 $log;
  fi;
  echo `date +"%d-%m-%Y %T"`" "$1;
  echo `date +"%d-%m-%Y %T"`" "$1 >> $log;
}

if [ -e $sdcache ]; then
  echo 2048 > $sdcache;
fi;

if [ ! -e $extblock ]; then
  logger "E/ "$extblock" block not found.";
  exit;
fi;
if [ ! -d $sdext ]; then
  logger "D/Creating external mount point on "$sdext;
  $bb mount -o rw,remount /;
  $bb mkdir $sdext;
  $bb mount -o ro,remount /;
else
  $bb umount $sdext;
fi;
logger "D/Mounting "$internal" --> "$sdext;
$bb umount /data;
$bb mount $internal $sdext;
logger "D/Mounting "$extblock" --> /data";
$bb mount -o noatime,nodiratime,nosuid,nodev $extblock /data;
$bb chown system:system /data;
$bb chmod 771 /data;
logger "D/Moving from "$sdext" --> /data";
$bb mv $sdext/* /data;

# move back for fixing radio signal error (wifi, mobile, IMEI bugs)
for h in misc radio property; do
  if [ ! -d $sdext/$h ]; then
    $bb mkdir $sdext/$h;
  fi;
  logger "D/Moving back "/data/$h" to "$sdext/$h;
  if [ -d /data/$h ]; then
    $bb mv /data/$h/* $sdext/$h;
  fi;
  if [ ! -d /data/$h ]; then
    $bb mkdir /data/$h;
  fi;
  $bb mount -o bind $sdext/$h /data/$h;
done;

# move back & sym-linked dalvik-cache to maintain performance (adapted from D2EXT)
if [ -d /data/dalvik-cache ]; then
  if [ ! -d $sdext/dalvik-cache ]; then
    $bb mkdir $sdext/dalvik-cache;
  fi;
  for i in `$bb ls /data/dalvik-cache`; do
    logger "D/Moving /data/dalvik-cache/"$i" --> "$sdext/dalvik-cache;
    $bb mv /data/dalvik-cache/$i $sdext/dalvik-cache;
    logger "D/Sym-linking "$sdext"/dalvik-cache/"$i" --> /data/dalvik-cache/"$i;
    $bb ln -sf $sdext/dalvik-cache/$i /data/dalvik-cache/$i;
  done;
fi;

$bb umount $sdext;
$bb sync;
